language: r
r:
  - release
  - devel
  - bioc-release

sudo: required
cran: http://cran.at.r-project.org

cache: packages

os:
- linux

after_success:
  - Rscript -e 'library(covr);codecov()'
  
notifications:
  email:
    on_success: change
    on_failure: always