language: r
r:
  - devel
  - release
  
r_github_packages:
  - jimhester/covr

r_check_args: "--as-cran"

before_install:
  - Rscript -e "install.packages('BiocManager')"
  - Rscript -e "BiocManager::install(c('zlibbioc', 'phyloseq', 'biomformat'), version = '3.14')"

# bioc_required: false
# bioc_use_devel: true
# bioc-packages: BiocManager, zlibbioc, phyloseq, biomformat

sudo: false
cran: http://cran.at.r-project.org

cache: packages

os:
- linux

after_success:
  - Rscript -e 'library(covr);codecov()'
  
notifications:
  email:
    on_success: change
    on_failure: always
    
  
  